### ISSUE TITLE
Output error following tutorial with Perseus

### ISSUE THREAD

**Issue by Jonathan-Davey** [jdrudolph/photon#18]
Hi,

At the step of performing the PHOTON analysis in Perseus, this output error is thrown (attached).
![errorcapture](https://user-images.githubusercontent.com/42599826/44445773-b4ac6d80-a625-11e8-92dc-cd1d85545cab.JPG)

Any help/advice to resolve this would be great.

Cheers

**Comment by jdrudolph** [comment]
Could you please check which version of Python you are using?
A syntax error in the `print` function smells like you are using Python 2.7 which reaches [end of life](https://pythonclock.org/) and is not supported in PHOTON / Perseus inter-operability. If this is indeed the case, please update to Python 3+, otherwise comment here again and we'll solve the issue.
