### ISSUE TITLE
Two of three sidedness options producing errors

### ISSUE THREAD

**Issue by jonhsussman** [jdrudolph/photon#19]
The default, greater sidedness option works without producing an error, however the lesser sidedness option and two-sided options each produce a different error. 
The lesser sided option produces the following error: no significant signaling functionality scores found, possibly due to insufficient data. 
The two sided option produces the following error: side parameters has to be one of "greater", "twosided", "less", was two-sided. 

Is this a glitch or can you suggest a possible solution for this problem? 

Thanks, 
Jonathan

**Comment by jdrudolph** [comment]
I was unable to reproduce the errors you describe with the latest development version of PluginPHOTON on my computer.

The "no significant signaling functionality scores found, possibly due to insufficient data." can be expected in some cases.

Could you try again after replacing the dlls in the `Perseus\bin` folder?
https://drive.google.com/file/d/1i0Bs3zOe9LMbL9L52qA_1QzfFFzwxFa6/view?usp=sharing

**Comment by jonhsussman** [comment]
Thanks for the information. 

The errors occurred while running it through Docker based on the instruction in the README.md file.

 I will try running PluginPHOTON through Perseus and see if that resolves the error.
