### ISSUE TITLE
Container stopps working immediately

### ISSUE THREAD

**Issue by isas-institute** [jdrudolph/photon#2]
Hello Jan,

I try to get this container running for one of my scientifical colleagues. Unfortunately it immediately stopps working after starting it. I think the container does not find the run.sh script defined in the dockerfile:

`ENTRYPOINT ["./run.sh"]`

Errormessage:
`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"./run.sh\\\": stat ./run.sh: no such file or directory\"\n".`

Do you have an idea how to fix it?

With Kind regards,

Christian

**Comment by jdrudolph** [comment]
I don't know how to reproduce this error, since the container works on my systems (tried Ubuntu and Win10). I'm not an Docker expert and have never seen this kind of error before. Googling the error message didn't yield a precise hit, but maybe have a look yourself...

In order to make sure that the problem is not with you Docker installation, could you maybe try to run some other docker image, e.g. from one of the various docker tutorials out there e.g. `docker run hello-world`?

**Comment by isas-institute** [comment]
Our other docker images are working correctly. Maybe I will try to install the software on a virtual machine next week. Anyway, thanks for your efforts!

**Comment by jdrudolph** [comment]
@isas-institute if you still encounter issues, please contact me again!
