### ISSUE TITLE
 Cannot proceed through (Network → From matrix → Basic → From matrix)

### ISSUE THREAD

**Issue by Mindianli** [jdrudolph/photon#28]
Dear Jan,

I had a problem converting the StringDB PPI from matrix to network when following your tutorial on " Integrated network analysis of EGF and IGF stimulation using PHOTON".  The Perseus version is 1.6.10.50. The error message is attached. 

Thank you very much!
Min

![微信截图_20200322092330](https://user-images.githubusercontent.com/49498869/77240408-63f56000-6c20-11ea-99c2-13d68b7d8297.png)

**Comment by jdrudolph** [comment]
Thanks you for reporting this issue. This is related to `Perseus` and not specific to Perseus. I forwarded your report to the Perseus developers.
You might also consider contributing to the discussion on the same issue on the mailing list https://groups.google.com/forum/#!topic/perseus-list/R-ugG7IfiX8
Since I don't see any way for me to resolve this issue within `photon_ptm` I will close this issue.
Best, Jan
