### ISSUE TITLE
Can not find photon in Perseus

### ISSUE THREAD

**Issue by Nazaninfarid** [jdrudolph/photon#37]
Dear Jan
I need to use photon and Perseus for my analysis. According to the installation guide, I have installed Photon and Perseus and python, but the photon is not available in my Perseus>Network>Modification.
Can you please help that how can I access it?
I attached a photo as well
Thank you very much

<img width="547" alt="error3" src="https://user-images.githubusercontent.com/38557924/120934376-74e3a180-c6fe-11eb-8229-2b5a73c2c922.PNG">

**Comment by jdrudolph** [comment]
Hi,
since this issue can stem from a lot of different issues I'd like to refer you to the Perseus community for help: https://groups.google.com/forum/#!forum/perseus-list since I don't believe that the issue is related to the PHOTON code itself.
Please make sure to use the latest version of Perseus from the https://maxquant.org/perseus website.

Best, Jan

**Comment by Nan-Y** [comment]
Hi,
I also had same issue with Perseus 1.6.15.0. After looking through messages in Perseus help community, I found this: https://groups.google.com/g/perseus-list/c/owbmuY3Q9Iw/m/J_8TxxG_CwAJ, with old versions of Perseus to download. I tried version 1.6.14.0 and Photon is available in this version. Hope this helps.
Best

**Comment by Nazaninfarid** [comment]
Hi @Nan-Y 
Thank you very much for you answer, it was more than a month that I was searching how to deal with this issue. 
I really appreciate it.
All the Best,
